### PR TITLE
SHA1 optimization

### PR DESCRIPTION
**Pull request by Merenon**
Short description:
https://crypto.beer/additional-slight-optimization-of-jens-steubes-sha1-message-expansion-attack/

### CODE REVIEW

**Comment by philsmd** [comment]
Are you sure this is related to md5 at all (the title says "Md5 optimization")?
Even if just the title is wrong and it is all about SHA1, how did you test the speed gains? Did you benchmark it? (I know the optimization is by Jens aka atom, yeah this project leader!).

One of the main problems could be register pressure etc. Implementing optimizations only make sense if it leads to a general speedup. Not all optimizations work on all platforms (e.g. cpu/gpu). Do you have some benchmarking numbers?

**Comment by gm4tr1x** [comment]
Hi, the "Word Expansion / XOR groups" optimization has been made by me 3 years ago.
What @Merenon found is well known but it was not applied for problems related to the performance. As @philsmd say, please do some benchmarks and post the results here.

**Comment by Merenon** [comment]
Hi, of course, you're right, it's related to SHA1 (I changed the title).
I will do some benchmark tests and post them. Thanks for your comments.

**Comment by magnumripper** [comment]
You could obviously do something like this (given there is some macro(s) usable for selecting platforms where this does improve performance).
```c
#if __this_or_that__
const u32x w0s07___w0s12 = w0s07 ^ w0s12;
#else
#define w0s07___w0s12 w0s07 ^ w0s12
#endif
```
It'd still not be a 100% no-op for the else clause (due to different ordering) but that should not be much of a problem.

**Comment by jsteube** [comment]
There was alot of changes due to due Get rid of CUDA branch. Please send in a new PR based on the current master

**Pull request closed without merging**
